export const smartDescriptions = {
  // Simple keys for the summary table (SMART Details)
  "health": "General status of the disk determined by its self-test. FAILING indicates imminent drive failure.",
  "temperature": "Current internal temperature of the drive. High temperatures (> 50°C) can accelerate disk degradation.",
  "model": "Manufacturer model identifier of the disk.",
  "size": "Total physical capacity of the drive.",
  "type": "Connection or technology type (e.g. SSD, HDD, NVMe).",
  "available": "Remaining storage capacity available on mounted partitions.",
  "total": "Total capacity of mounted partitions.",
  "usage": "Percentage of storage partition currently in use.",
  "reallocated": "Reallocated Sector Count: The number of damaged sectors that have been remapped to a spare area. A value greater than 0 indicates physical disk degradation and potential failure.",
  "pending": "Current Pending Sector Count: The number of unstable sectors waiting to be remapped. If subsequent reads succeed or writes remap it, the count decreases.",
  "offline unc.": "Offline Uncorrectable Sector Count: The number of uncorrectable errors when reading/writing sectors. A high count indicates serious media degradation.",
  "crc errors": "UDMA CRC Error Count: The number of data errors during transmission over the interface cable. High counts usually point to a faulty SATA cable/port.",

  // Exact ATA SMART Attribute Name mappings for "View SMART attributes" table
  "raw_read_error_rate": "Rate of hardware read errors that occurred when reading data from the disk surface. High values point to head or disk surface problems.",
  "spin_up_time": "Average time it takes the spindle to spin up from zero to full speed. Slow times can indicate motor degradation.",
  "start_stop_count": "Total start/stop cycles of the spindle motor.",
  "reallocated_sector_ct": "Reallocated Sector Count: Number of damaged sectors remapped to a spare area. A value > 0 indicates physical disk degradation and potential failure.",
  "seek_error_rate": "Rate of seek errors of the magnetic heads. High rates indicate head positioning issues or thermal expansion.",
  "power_on_hours": "Accumulated power-on lifetime of the drive in hours.",
  "spin_retry_count": "Number of retries of spin start attempts. High counts indicate mechanical degradation of the motor.",
  "power_cycle_count": "Number of full power-on/off cycles of the drive.",
  "runtime_bad_block": "Number of bad blocks encountered during runtime operation.",
  "end-to-end_error": "Number of parity errors in the drive's data cache buffer. Non-zero indicates potential controller failures.",
  "reported_uncorrect": "Number of read/write errors that could not be recovered using hardware ECC.",
  "command_timeout": "Number of aborted operations due to HDD timeout. Can point to power supply or cable issues.",
  "high_fly_writes": "Number of write operations aborted because the magnetic head is flying outside its safe operational height.",
  "airflow_temperature_cel": "Internal temperature of the drive's airflow. Should match temperature values.",
  "temperature_celsius": "Current internal temperature of the drive.",
  "g-sense_error_rate": "Number of seek errors resulting from externally induced shock or vibration.",
  "power-off_retract_count": "Number of times the heads were safely parked due to sudden power loss.",
  "load_cycle_count": "Number of times the heads were loaded/unloaded into the landing zone.",
  "current_pending_sector": "Current Pending Sector Count: Number of unstable sectors waiting to be remapped. Indicates potential upcoming bad sectors.",
  "offline_uncorrectable": "Offline Uncorrectable Sector Count: Number of uncorrectable errors when reading/writing sectors. A high count indicates serious media degradation.",
  "udma_crc_error_count": "UDMA CRC Error Count: Number of data errors during transmission over the interface cable. High counts usually point to a faulty SATA cable/port.",
  "multi_zone_error_rate": "Rate of write errors occurring in multiple zones of the disk.",

  // NVMe SMART log fields (Key mappings)
  "critical warning": "Indicates critical status warnings for the controller (e.g., temperature threshold exceeded, media errors). Value should be 0.",
  "criticalwarning": "Indicates critical status warnings for the controller (e.g., temperature threshold exceeded, media errors). Value should be 0.",
  "available spare": "Percentage of remaining spare capacity available for remapping bad sectors. Should ideally be 100%.",
  "availablespare": "Percentage of remaining spare capacity available for remapping bad sectors. Should ideally be 100%.",
  "available spare threshold": "Threshold of available spare space. When available spare falls below this, a critical warning is triggered.",
  "availablesparethreshold": "Threshold of available spare space. When available spare falls below this, a critical warning is triggered.",
  "percentage used": "Life consumption estimate of the NVM subsystem. 100% means the device has reached its estimated endurance limit.",
  "percentageused": "Life consumption estimate of the NVM subsystem. 100% means the device has reached its estimated endurance limit.",
  "data units read": "Accumulated data read from the controller (usually formatted as TB/GB).",
  "dataunitsread": "Accumulated data read from the controller (usually formatted as TB/GB).",
  "data units written": "Accumulated data written to the controller (usually formatted as TB/GB).",
  "dataunitswritten": "Accumulated data written to the controller (usually formatted as TB/GB).",
  "host read commands": "Total read commands processed by the controller.",
  "hostreadcommands": "Total read commands processed by the controller.",
  "host write commands": "Total write commands processed by the controller.",
  "hostwritecommands": "Total write commands processed by the controller.",
  "controller busy time": "Time (in minutes) the controller has been busy processing commands.",
  "controllerbusytime": "Time (in minutes) the controller has been busy processing commands.",
  "power cycles": "Number of power cycles the drive has experienced.",
  "powercycles": "Number of power cycles the drive has experienced.",
  "power on hours": "Accumulated power-on time of the drive in hours.",
  "poweronhours": "Accumulated power-on time of the drive in hours.",
  "unsafe shutdowns": "Number of power-downs without a preceding shutdown notification command.",
  "unsafeshutdowns": "Number of power-downs without a preceding shutdown notification command.",
  "media and data integrity errors": "Number of occurrences where the controller detected data integrity errors.",
  "mediaanddataintegrityerrors": "Number of occurrences where the controller detected data integrity errors.",
  "error information log entries": "Number of error information log entries generated by the controller.",
  "errorinformationlogentries": "Number of error information log entries generated by the controller."
};
