export const smartDescriptions = {
  "health": "General status of the disk determined by its self-test. FAILING indicates imminent drive failure.",
  "temperature": "Current internal temperature of the drive. High temperatures (> 50°C) can accelerate disk degradation.",
  "model": "Manufacturer model identifier of the disk.",
  "size": "Total physical capacity of the drive.",
  "type": "Connection or technology type (e.g. SSD, HDD, NVMe).",
  "available": "Remaining storage capacity available on mounted partitions.",
  "total": "Total capacity of mounted partitions.",
  "usage": "Percentage of storage partition currently in use.",
  "reallocated": "Reallocated Sector Count: The number of damaged sectors that have been remapped to a spare area. A value greater than 0 indicates physical disk degradation and potential failure.",
  "pending": "Current Pending Sector Count: The number of unstable sectors waiting to be remapped. If subsequent reads succeed or writes remap it, the count decreases.",
  "offline unc.": "Offline Uncorrectable Sector Count: The number of uncorrectable errors when reading/writing sectors. A high count indicates serious media degradation.",
  "crc errors": "UDMA CRC Error Count: The number of data errors during transmission over the interface cable. High counts usually point to a faulty SATA cable/port.",
  
  // NVMe specific keys
  "critical warning": "Indicates critical status warnings for the controller (e.g., temperature threshold exceeded, media errors). Value should be 0.",
  "percentage used": "Life consumption estimate of the NVM subsystem. 100% means the device has reached its estimated endurance limit.",
  "data units read": "Accumulated data read from the controller.",
  "data units written": "Accumulated data written to the controller.",
  "host read commands": "Total read commands processed by the controller.",
  "host write commands": "Total write commands processed by the controller.",
  "controller busy time": "Time (in minutes) the controller has been busy processing commands.",
  "power cycles": "Number of power cycles the drive has experienced.",
  "power on hours": "Accumulated power-on time of the drive in hours.",
  "unsafe shutdowns": "Number of power-downs without a preceding shutdown notification command.",
  "media and data integrity errors": "Number of occurrences where the controller detected data integrity errors.",
  "error information log entries": "Number of error information log entries generated by the controller."
};
